[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
criterion = { workspace = true }
soroban-sdk = { version = "22.0.0", features = ["testutils"] }
invoice = { path = "../contracts/invoice" }
pool = { path = "../contracts/pool" }
share = { path = "../contracts/share" }

[[bench]]
name = "contract_benchmarks"
harness = false
